#!/bin/sh

SERVICE="com.system76.SystemUpdater"
SESSION="${SERVICE}.Local"

systemctl daemon-reload

if systemctl is-active "${SERVICE}"; then
    systemctl restart "${SERVICE}"
fi

systemctl enable --now "${SERVICE}"
systemctl --global enable "${SESSION}"

#DEBHELPER#

exit 0